### ISSUE TITLE
If flat=True, I want to add one more field to merge two lists & provide a custom merge function

### ISSUE THREAD

**Issue by anujism** [Axiologue/DjangoRestMultipleModels#11]
How can I extend this to add a new field based on which return the results?

For eg. before calling queryList_sort function, I would like to call a custom queryList_merge function.

**Comment by MattBroach** [comment]
That should be a pretty easy refactor: I'll just move the merging process to a separate function that you'll be able to overwrite in your view.  I'm a little swamped this week, but I'll get to this over the weekend.  I'll also add an example of using `filter_fn` to the documentation, per your other request.

**Comment by MattBroach** [comment]
Sorry for the delay -- took me awhile to find the time to make an update.  I have moved part of the mixin into a `format_data()` function, which handles how serialized data is formatted and combined in the running total.  You should be able to override that in your specific view to get the functionality you're looking for.

**Comment by anujism** [comment]
Thanks. This is exactly what I needed. This library is a great help.
