### ISSUE TITLE
mixedCase usage?

### ISSUE THREAD

**Issue by diego351** [Axiologue/DjangoRestMultipleModels#13]
Hi, nice job! Question regarding naming - is there any particular reason to write 'queryList' using Camel?

**Comment by MattBroach** [comment]
Hey, good question!  My main rational was to make it more visually distinct from `queryset`, which is used all over the place in django and DRF.  `querylist` might be missed/passed over if scanning quickly over a bunch of code, whereas `queryList` reads as more distinct.

I agree it's not really "pythonic" naming and I'm not dogmatic about it, but at this point I think there are enough people using the library that I'd prefer not to change the base naming structure.
