### ISSUE TITLE
Fix for #1 broke ability to have cached querylists

### ISSUE THREAD

**Issue by mbox** [Axiologue/DjangoRestMultipleModels#17]
See comment on #1 - because querysets are all forced to be re-evaluated, it's now impossible to cache the DB queries which is essential for some users (e.g. me :) )

**Comment by MattBroach** [comment]
@mbox, thanks for the fix -- and for the bonus PEP8-ification.  I merged into master, and I'll repackage and push the new version out to PyPI tonight.  Much appreciated!
