### ISSUE TITLE
Nested relationships GenericRelatedObjectManager object is not JSON serializable

### ISSUE THREAD

**Issue by awolfmann** [Axiologue/DjangoRestMultipleModels#19]
I have a nested relationship defined as here: [http://www.django-rest-framework.org/api-guide/relations/#nested-relationships](url)

When i use MultipleModelAPIView i'm getting TypeError: GenericRelatedObjectManager object is not JSON serializable, but the same serializers works fine in the generics.ListAPIView, and viewsets.ModelViewSet

Any idea?

**Comment by MattBroach** [comment]
Hey @awolfmann: I noticed you closed this pretty soon after opening it.  I just wanted to check to make sure you actually got your problem sorted out!

**Comment by awolfmann** [comment]
Hey @MattBroach thanks for writing! Yes, after just some hours i have opened the issue, i fixed the problem, it was my mistake with some of the serializers i used on the view.

Thanks again!

**Comment by MattBroach** [comment]
Cool!  Glad you got it sorted out.
